### ISSUE TITLE
the iGPU work?

### ISSUE THREAD

**Issue by pprice2018** [1gjunior/Ryzen_5_2400G-RX_480-Hackintosh#1]
the iGPU work?

**Comment by 1gjunior** [comment]
Yes but you will only have 4-7MB of dvmd ram support.  IT will do simple browsing but it will have artifacts.  Its not ideal and you should Duse a dedicated graphics card for running any major apps.

follow this issue for more details
https://github.com/mvaisakh/Asus-X505ZA-Ryzen-Hackintosh/issues/1
